---
title: "November 3"
author: "Jim Albert"
date: "2022-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Resources

A brief introduction to R using baseball data is contained in Chapter 2 of *Analyzing Baseball Data With R*, 2nd edition.  A general introduction to R using the `tidyverse` collection of packages is in the *R for Data Science* book available online at https://r4ds.had.co.nz/

I will maintain a Github repository containing all of the Markdown files I create.  It can be found at

https://github.com/bayesball/HUGO

### Getting Started with R and RStudio

- Install R from https://cran.r-project.org/ 

- RStudio Desktop from https://posit.co/products/open-source/rstudio/

(The company is now called Posit, the product is still RStudio.)

- Install R packages as needed.  (Recommend installing tidyverse and Lahman packages right away)

- Will generally work in Markdown documents -- this allows one to mix text and R work in a single file.

### Examples of Working with Datasets in Lahman Package

- Top_AVG.Rmd -- example of working with Batting data frame in Lahman package

- World_Series.Rmd - example of working with several post-season data frames in Lahman package

### On Your Own

Here are some questions to explore on several datasets from the Lahman package. Feel free to ask me any questions (by email at albert@bgsu.edu) you have before our next online meeting.

#### Exploring Pitching data frame

Pitching is a data frame with 48,399 observations and 30 variables.  A row consists of stats for a specific pitcher for a given season and stint (if a player is traded midseason, he may have several stints within a single season).

1.  Assuming at least 100 innings pitched, who had the best season ERA in all seasons 1960 or later?

2.  Again assuming at least 100 innings pitched and seasons 1960 or later, who had the best season WHIP value?

3.  Considering all seasons 1960 or later, which pitcher had the best career WHIP measure?

4.  Suppose you are interested in a pitchers ratio of strikeouts to walks.  For the 2000 season, which pitcher had the best SO / BB ratio?  (Assume at least 100 innings pitched.)

#### Exploring Teams data frame

Teams is a data frame with 2985 observations and 48 variables.  A row consists of season records for a given team in a given season.

1.  Which team had the best win/loss percentage in a single season?

2.  Find the 10 teams who had the best win/loss records in a single season since 1920.  How many of these teams won the World Series?

3.  One can compute the expected number of wins for a team by use of the Bill James formula:

$$
E = G \times \frac{R^2}{R^2 + RA^2}
$$

One can measure a team's success by seeing how many wins a team has above expected.

$$
Luck = W - E
$$

For all teams in seasons 1960 or later, which teams had the highest Luck values?  Which teams had the lowest Luck values?

